In [11]:
import numpy as np

In [12]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
print(np.__version__)

2.5.1


In [14]:
print(a.shape)
print(a.dtype)
print(a.size)
print(type(a))
print(a.ndim)
print(a.itemsize)

(7,)
int64
7
<class 'numpy.ndarray'>
1
8


In [15]:
print(a.size)
print(a.ndim)
print(a.itemsize)
print(a.nbytes)
print(a.data)
print(a.base)
print(a.flags)
print(a.strides)
print(a.ctypes)
print(a.tobytes())
print(a.tolist())
print(a.shape)
print(a.dtype)

7
1
8
56
None
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

(8,)
b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00'
[1, 2, 3, 4, 5, 6, 7]
(7,)
int64


Basic terms Clarification


In [16]:
scalar = np.array(5)
vector = np.array([1,2,3,4,5])
matrix = np.array([[1,2,3],[4,5,6]])
tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [17]:
print(scalar)
print(vector)
print(matrix)
print(tensor)

5
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [18]:
print(scalar.ndim)
print(vector.ndim)
print(tensor.ndim)


0
1
3


In [19]:
p2_tensor = ([[[1,2,3,2],[3,4,5,6],[9,8.6,6],
[4,5,6,],[9,8,6,2],[7,1,4,5]
]])

In [20]:
tensor_p = np.array([
    [[1,2,3],[4,5,6]],
    [[6,7,8],[9,3,1]]
])

In [21]:
print(tensor_p)

[[[1 2 3]
  [4 5 6]]

 [[6 7 8]
  [9 3 1]]]


In [22]:
print(tensor_p.shape)

(2, 2, 3)


In [23]:
arr = np.array([1,2,3,4,"Ali","is a good boy and he goes to"])
arr

array(['1', '2', '3', '4', 'Ali', 'is a good boy and he goes to'],
      dtype='<U28')

In [24]:
print(arr.dtype)

<U28


In [25]:
arr_2 = np.array([1,2,3,4,5,6,6,7,7], dtype=np.int8)
print(arr_2.dtype)
print(arr_2.itemsize)

int8
1


arange = Same as slicing gives a ranges of numbers with this syntax:
start:stop:step

In [26]:
ar = np.arange(1,100,1)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

linspace = it is differ from arange and gives number between given range
like it will generate 100 numbers in a range of 0 and 1

In [27]:
linspace = np.linspace(0,1,50)
linspace

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [28]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
zero_matrix = np.zeros((10,10))
zero_matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
zero_tensor = np.zeros((2,10,12))
zero_tensor

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0.,

In [31]:
full = np.full((10,5),0)
full

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
ones = np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
eye = np.eye(5)
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
random = np.random.rand(3,4)
random

array([[0.03734098, 0.84814432, 0.25383997, 0.36935849],
       [0.96538936, 0.50654683, 0.847677  , 0.07449943],
       [0.20910663, 0.63989775, 0.4453172 , 0.24387314]])

In [37]:
random = np.random.rand(3,4)
random

array([[0.76712888, 0.30429856, 0.69392454, 0.25703987],
       [0.20970914, 0.67077759, 0.86172164, 0.95805012],
       [0.86108612, 0.38535848, 0.95820528, 0.28641535]])

In [38]:
random1 = np.random.randn(3,4)
random1

array([[-0.51643434, -0.2992559 ,  1.09282229,  0.19870073],
       [ 0.93560263, -1.9825794 ,  0.21063747,  0.35710101],
       [ 1.16112429,  0.94411419,  0.43645945, -1.22346126]])

In [41]:
random2 = np.random.randint(1,20,6)
random2

array([ 2, 16, 10, 14,  3, 15], dtype=int32)

In [46]:
# normal(meann(loc), scale(std), shape(rows,columns))
random3 = np.random.normal(1,1,(3,3))
random3

array([[ 0.43716246,  2.21721945,  0.55100202],
       [ 1.12373635, -0.66289311,  1.91642037],
       [ 2.24718107, -0.04500828,  2.36096712]])

In [47]:
import pandas as pd

In [52]:
series = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [53]:
pd.Series(series.shape)

0    5
dtype: int64

In [54]:
pd.Series(series.dtype)

0    int64
dtype: object

In [55]:
pd.Series(series.size)

0    5
dtype: int64

In [56]:
pd.Series(series.describe)

0    <bound method NDFrame.describe of a    1\nb   ...
dtype: object