How can we set explicit data type in NumPy

In [2]:
import numpy as np
np

<module 'numpy' from 'c:\\Users\\LAPTOP GENERATION\\miniconda3\\envs\\python-ai\\Lib\\site-packages\\numpy\\__init__.py'>

In [4]:
arr = np.array([1,2,3,4,5], dtype=np.int8)
print(arr.dtype)
print(arr.itemsize)

int8
1


Slicing
arr[start:stop:step]

In [6]:
vector = np.arange(30)
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
vector[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [8]:
vector[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [9]:
vector[5::2]

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

Multidimensional Slicing
tensor[sheet:row:col]

In [12]:
tensor = np.arange(300).reshape(20,3,5)
tensor

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14]],

       [[ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44]],

       [[ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104]],

       [[105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119]],

       [[120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134]],

       [[135, 136, 137, 138, 139],
  

In [14]:
matrix = np.arange(30).reshape(5,6)
matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [15]:
matrix[1:4,2:4]

array([[ 8,  9],
       [14, 15],
       [20, 21]])

In [18]:
matrix[1:4,]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [19]:
tensor

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14]],

       [[ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44]],

       [[ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104]],

       [[105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119]],

       [[120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134]],

       [[135, 136, 137, 138, 139],
  

In [20]:
tensor[15::,1::,::2]

array([[[230, 232, 234],
        [235, 237, 239]],

       [[245, 247, 249],
        [250, 252, 254]],

       [[260, 262, 264],
        [265, 267, 269]],

       [[275, 277, 279],
        [280, 282, 284]],

       [[290, 292, 294],
        [295, 297, 299]]])

In [21]:
tensor[10:14:,2:4:,1:3:]

array([[[161, 162]],

       [[176, 177]],

       [[191, 192]],

       [[206, 207]]])

In [22]:
tensor[9:12:,1:3:,1::]

array([[[141, 142, 143, 144],
        [146, 147, 148, 149]],

       [[156, 157, 158, 159],
        [161, 162, 163, 164]],

       [[171, 172, 173, 174],
        [176, 177, 178, 179]]])