In [215]:
import numpy as np

Q1:Import NumPy using its conventional alias and create a one-dimensional NumPy array containing 10, 20, 30, 40, 50. Print the array.

In [216]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


Question 2 Create a NumPy array containing the numbers from 1 to 20 using an appropriate NumPy helper function.

In [217]:
arr1 = np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Question 3 Create the following arrays: (a) an array of five zeros, (b) an array of six ones, (c) an array containing five elements initialized with the value 7.

In [218]:
arr2 = np.zeros(5)
print(arr2)

arr3 = np.ones(6)
print(arr3)

arr4 = np.full(5,7)
print(arr4)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[7 7 7 7 7]


Question 4 Create a NumPy array of ten random integers between 1 and 100. 

In [219]:
arr5 = np.random.randint(1,101,10)
arr5

array([69, 46, 87, 35, 20, 40, 19, 55, 57,  9], dtype=int32)

Question 5 Create an array containing 10 equally spaced values between 0 and 1. 

In [220]:
arr6 = np.linspace(0,1,10)
arr6

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Question 6 Create a 3 × 3 identity matrix using NumPy.

In [221]:
matrix = np.eye(3,3)
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Question 7 Given: arr = np.array([[10, 20, 30], [40, 50, 60]]) Find: (a) number of dimensions, (b) shape, (c) total number of elements, (d) data type. 

In [222]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[10 20 30]
 [40 50 60]]
2
(2, 3)
6
int64


Question 8 Given: arr = np.array([10, 20, 30, 40, 50, 60, 70]) Retrieve: (a) first element, (b) last element, (c) third element, (d) second-last element. 

In [223]:
arr = np.array([10,20,30,40,50,60,70])
arr
print(arr[0])
print(arr[-1])
print(arr[2])
print(arr[-2])

10
70
30
60


Using negative indexing on: arr = np.array([10, 20, 30, 40, 50, 60, 70]) retrieve: (a) last element, (b) third-last element, (c) first element.

In [224]:
arr = np.array([10,20,30,40,50,60,70])
arr
print(arr[-1])
print(arr[-3])
print(arr[-7])


70
50
10


Question 10 Given: arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]) Use indexing to retrieve: 10, 50, 90, 30, and 70. 

In [225]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)
print(arr[0,0])
print(arr[1,1])
print(arr[2,2])
print(arr[2,0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
50
90
70


Question 11 Given: arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) Retrieve using indexing: 1, 6, 8, 10, and 12. 

In [226]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) 
print(arr)
print(arr[0,0])
print(arr[1,1])
print(arr[1,3])
print(arr[2,1])
print(arr[2,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
6
8
10
12


Question 12 Given: arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]) Retrieve the complete first row, second row, third row, and last row. 

In [227]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(arr)
print(arr[0,0:5])
print(arr[1,0:5])
print(arr[2,0:5])
print(arr[3,0:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]


We can also solve the previous question like this:

In [228]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]


Question 13 Using the same array, retrieve the complete first column, second column, third column, and last column. 

In [229]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(arr[:,0])
print(arr[:,1])
print(arr[:,2])
print(arr[:,3])
print(arr[:,4])

[ 1  6 11 16]
[ 2  7 12 17]
[ 3  8 13 18]
[ 4  9 14 19]
[ 5 10 15 20]


Question 14 Given: arr = np.array([10, 20, 30, 40, 50, 60, 70, 80]) Use slicing to retrieve: (a) first three elements, (b) last three elements, (c) elements from index 2 to 5, (d) elements from index 1 to 6.

In [230]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80]) 
print(arr[0:3])
print(arr[-3::])
print(arr[2:6:])
print(arr[1:7:])

[10 20 30]
[60 70 80]
[30 40 50 60]
[20 30 40 50 60 70]


Question 15 Using the same array, retrieve: (a) every second element, (b) every third element, (c) elements from index 0 to 5 with a step of 2, (d) elements from index 1 to 7 with a step of 2. 

In [231]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80]) 
print(arr[::2])
print(arr[::3])
print(arr[0:5:2])
print(arr[1:7:2])

[10 30 50 70]
[10 40 70]
[10 30 50]
[20 40 60]


Question 16 Given: arr = np.arange(1, 21) Use slicing to retrieve: (a) first five numbers, (b) last five numbers, (c) numbers from 5 to 15, (d) every second number, (e) every third number.

In [232]:
arr = np.arange(1,21)
print(arr)
print(arr[0:5:])
print(arr[-5::])
print(arr[4:15:])
print(arr[::2])
print(arr[::3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[1 2 3 4 5]
[16 17 18 19 20]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 1  3  5  7  9 11 13 15 17 19]
[ 1  4  7 10 13 16 19]


Question 17 Given: arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]) Use slicing to retrieve: (a) first two rows, (b) last two rows, (c) first three rows, (d) last three rows. 

In [233]:
arr =  np.array([
[1, 2, 3, 4, 5], 
[6, 7, 8, 9, 10], 
[11, 12, 13, 14, 15], 
[16, 17, 18, 19, 20]]) 
print(arr)

print(arr[0:2,])
print(arr[-2:,])
print(arr[0:3:,])
print(arr[:,-1:-3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[]


Question 18 Using the same array, retrieve: (a) first two columns, (b) last two columns, (c) first three columns, (d) columns 2 through 4. 

In [234]:
arr =  np.array([
[1, 2, 3, 4, 5],
[6, 7, 8, 9, 10], 
[11, 12, 13, 14, 15],
[16, 17, 18, 19, 20]]) 
print(arr)
print("\n")
print(arr[:,-1:-3:-1])

print(arr[:,0:2:])

print(arr[:,-2::])
print(arr[:,0:3:])
print(arr[:,2:5:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


[[ 5  4]
 [10  9]
 [15 14]
 [20 19]]
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]]


Question 19 Extract the following submatrix using NumPy slicing: 7  8  9 12 13 14 17 18 19 

In [235]:
arr =  np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]) 
print(arr)

print(arr[1:4,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


Question 20 Extract the following submatrix using NumPy slicing: 2  3  4 7  8  9 12 13 14 

In [236]:
arr =  np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]) 
print(arr)

print(arr[0:3,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


Question 21 Given: arr = np.arange(1, 26).reshape(5, 5) Extract: (a) first 3 rows and first 3 columns, (b) last 3 rows and last 3 columns, (c) middle 3 × 3 region, (d) first 2 rows and last 2 columns. 

In [237]:
arr = np.arange(1,26).reshape(5,5)
print(arr)

# First 3 rows and first 3 columns
print(arr[0:3,0:3])
print(arr[-3::,-3::])
print(arr[1:4,1:4])
print(arr[0:2:,-2::])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
[[13 14 15]
 [18 19 20]
 [23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 4  5]
 [ 9 10]]


Question 22 arr = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12], [13,14,15,16,17,18], [19,20,21,22,23,24], [25,26,27,28,29,30], [31,32,33,34,35,36]]) Using the  array, extract: 1  3  5 13 15 17 25 27 29 using slicing. 

In [238]:
arr = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12], [13,14,15,16,17,18],
 [19,20,21,22,23,24], [25,26,27,28,29,30], [31,32,33,34,35,36]]) 

print(arr)

print(arr[0::2,0::2])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


Question 23 Given: arr = np.arange(1, 37).reshape(6, 6) Use slicing to extract: (a) top-left 3 × 3 section, (b) top-right 3 × 3 section, (c) bottom-left 3 × 3 section, (d) bottom-right 3 × 3 section

In [239]:
arr = np.arange(1,37).reshape(6,6)
print(arr)
# top-left 3 × 3 section
print(arr[0:3:,0:3:])
#  top-left 3 × 3 section
print(arr[0:3:,3::])
#  bottom-left 3 × 3 section
print(arr[3::,0:3])
#  bottom-right 3 × 3 section
print(arr[3::,3::])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
[[ 4  5  6]
 [10 11 12]
 [16 17 18]]
[[19 20 21]
 [25 26 27]
 [31 32 33]]
[[22 23 24]
 [28 29 30]
 [34 35 36]]


Given: arr = np.arange(1, 37).reshape(6, 6) Use slicing to select: (a) every second row, (b) every second column, (c) every second row and every second column. 

In [240]:
arr = np.arange(1,37).reshape(6,6)
print(arr)

# Every 2nd row
print(arr[0::2,])

# Every 2nd column
print(arr[:,0::2])

# Every 2nd row and every 2nd column
print(arr[0::2,0::2])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 1  2  3  4  5  6]
 [13 14 15 16 17 18]
 [25 26 27 28 29 30]]
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]
 [25 27 29]
 [31 33 35]]
[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


Question 25 array=np.arange(120, dtype=np.int16).reshape(8,5,3) extract [ 36,  37], [ 39,  40], And  [84,85,  86], [ 87,  88,  89

In [241]:
array=np.arange(120, dtype=np.int16).reshape(8,5,3)
print(array)

print(array[2,2:4:,0:2:])

print(array[5,3:5:, :])

[[[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]]

 [[ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]]

 [[ 30  31  32]
  [ 33  34  35]
  [ 36  37  38]
  [ 39  40  41]
  [ 42  43  44]]

 [[ 45  46  47]
  [ 48  49  50]
  [ 51  52  53]
  [ 54  55  56]
  [ 57  58  59]]

 [[ 60  61  62]
  [ 63  64  65]
  [ 66  67  68]
  [ 69  70  71]
  [ 72  73  74]]

 [[ 75  76  77]
  [ 78  79  80]
  [ 81  82  83]
  [ 84  85  86]
  [ 87  88  89]]

 [[ 90  91  92]
  [ 93  94  95]
  [ 96  97  98]
  [ 99 100 101]
  [102 103 104]]

 [[105 106 107]
  [108 109 110]
  [111 112 113]
  [114 115 116]
  [117 118 119]]]
[[36 37]
 [39 40]]
[[84 85 86]
 [87 88 89]]


In [242]:
arr = np.arange(1, 51).reshape(10, 5)
print(arr)

# Last 4 rows first 2 col
print("\n")
print(arr[-4::,0:2:])

# Every 3rd row and all col
print("\n")
print(arr[0::3,0::])

# The 3×3 submatrix in the exact center of the array
print("\n")
print(arr[4:7:,1:4:])

# A single "checkerboard-style" slice: every second row and every 
# second column, starting from row 1 and column 1 (not row 0)
print("\n")
print(arr[1::2,1::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


[[31 32]
 [36 37]
 [41 42]
 [46 47]]


[[ 1  2  3  4  5]
 [16 17 18 19 20]
 [31 32 33 34 35]
 [46 47 48 49 50]]


[[22 23 24]
 [27 28 29]
 [32 33 34]]


[[ 7  9]
 [17 19]
 [27 29]
 [37 39]
 [47 49]]


In [243]:
arr = np.arange(1, 26).reshape(5, 5)
print(arr)
print("\n")
print(arr[:,-4:-2])

print("\n")
print(arr[-2:,-2:])

print(arr[2:4:,1:3:])



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]]


[[19 20]
 [24 25]]
[[12 13]
 [17 18]]


In [244]:
arr = np.arange(1,81).reshape(5,4,4)
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]

 [[65 66 67 68]
  [69 70 71 72]
  [73 74 75 76]
  [77 78 79 80]]]


In [274]:
matrix1 = np.arange(30).reshape(5,6)
tensor = np.arange(72).reshape(3,6,4)
tensor_4d = np.array([[[[1,2,3],[1,2,3]],[[4,5,6],[1,2,3]],[[7,8,8],[1,2,3]]],[[[1,2,3],[1,2,3]],[[4,5,6],[1,2,3]],[[7,8,8],[1,2,3]]]])
ten = np.arange(24).reshape(2,3,2,2)


1,21,71,48

In [275]:
ten

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [278]:
ten[-1::-1,0:2:,0:1:,-1::-1]

array([[[[13, 12]],

        [[17, 16]]],


       [[[ 1,  0]],

        [[ 5,  4]]]])