In [88]:
import numpy as np
import pandas as pd


In [89]:
arr = np.array([
[[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]],
[[130, 140, 150, 160], [170, 180, 190, 200], [210, 220, 230, 240]],
[[250, 260, 270, 280], [290, 300, 310, 320], [330, 340, 350, 360]]
])

In [90]:
first = arr[0,1:3,1:3:]
first


array([[ 60,  70],
       [100, 110]])

In [91]:
second = arr[1,1:3,1:3:]
second

array([[180, 190],
       [220, 230]])

In [92]:
# # Q2. Fancy Indexing of 2D NumPy Array
# arr = np.array([
# [10, 20, 30, 40, 50],
# [60, 70, 80, 90, 100],
# [110, 120, 130, 140, 150],
# [160, 170, 180, 190, 200],
# [210, 220, 230, 240, 250]
# ])
# Using ONLY fancy indexing, write a NumPy expression that extracts:
# [20, 80, 140, 200, 210]



In [93]:
arr2 = np.array([
[10, 20, 30, 40, 50],
[60, 70, 80, 90, 100],
[110, 120, 130, 140, 150],
[160, 170, 180, 190, 200],
[210, 220, 230, 240, 250]
])

In [94]:
fancy_indexed = arr2[[0, 1, 2, 3, 4], [1, 2, 3, 4, 0]]
fancy_indexed

array([ 20,  80, 140, 200, 210])

Create a labeled DataFrame 4x3 from a dictionary, with indexes named Row1, Row2, … and columns named Col1, Col2, …. Then add one column and drop one row from it.



In [95]:
labelled_data = pd.DataFrame.from_dict({'Row1':[1, 2, 3], 'Row2':[4, 5, 6], 'Row3':[7, 8, 9],'Row4':[10, 11, 12]}, 
 orient='index', columns=['Col1', 'Col2', 'Col3'])

labelled_data

,Col1,Col2,Col3
Row1,1,2,3
Row2,4,5,6
Row3,7,8,9
Row4,10,11,12


In [96]:
# adding one col
labelled_data['Col4'] = [13, 14, 15, 16]
labelled_data

,Col1,Col2,Col3,Col4
Row1,1,2,3,13
Row2,4,5,6,14
Row3,7,8,9,15
Row4,10,11,12,16


In [98]:
# Drop one row
dropped = labelled_data.drop('Row2', axis=0, inplace=False)
dropped



,Col1,Col2,Col3,Col4
Row1,1,2,3,13
Row3,7,8,9,15
Row4,10,11,12,16
